name: Build and Push

on:
  push:
    branches:
      - main
  
  #TODO: To remove before final merge
  pull_request:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  ECR_PUBLIC_REGISTRY: public.ecr.aws/medic
  ECR_REPOSITORY: superset
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  build:
    name: Make docker file and publish
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        VERSION=$(grep -oP 'FROM\s+apache/superset:\K[^\s]+' Dockerfile)
        echo "VERSION=$VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon Public ECR
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws
        username: ${{ env.AWS_ACCESS_KEY_ID }}
        password: ${{ env.AWS_SECRET_ACCESS_KEY }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: | 
          ${{ env.ECR_PUBLIC_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
          ${{ env.ECR_PUBLIC_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.extract_version.outputs.version }}
          