name: Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_REPO_NAME: 'medicmobile/superset'

jobs:
  build:
    name: Make docker file and publish
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        VERSION=$(grep -oP 'FROM\s+apache/superset:\K[^\s]+' Dockerfile)
        echo "VERSION=$VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: | 
          ${{ env.DOCKERHUB_REPO_NAME }}:latest
          ${{ env.DOCKERHUB_REPO_NAME }}:${{ steps.extract_version.outputs.version }}